version: "2"

services:
    validate-s3:
        build: ${PROJECT_ROOT}/integ/s3
        environment:
            - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
            - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
            - "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}"
            - "AWS_REGION=${AWS_REGION}"
            - "S3_BUCKET_NAME=${S3_BUCKET_NAME}"
            - "S3_ACTION=${S3_ACTION}"
            - "S3_PREFIX=${S3_PREFIX}"
            - "TEST_FILE=${TEST_FILE}"
        volumes:
            - ${PROJECT_ROOT}/integ/out:/out
