version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13
      python: 3.x
  pre_build:
    commands:
      - echo Publish the image to Public ECR
      - pip3 uninstall awscli -y
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/bin --update
      - which aws
      - aws --version
  build:
    commands:
      # Pull and tag the images that we built and pushed in the `Build` stage
      - ./scripts/pipeline/sync-test-images.sh --tag

      # Assume role to publish, get the credentials, and set them as environment variables
      - |
        if [ "${PUBLISH_ROLE_ARN_PUBLIC_ECR}" != "" ]; then
          CREDS=`aws sts assume-role --role-arn ${PUBLISH_ROLE_ARN_PUBLIC_ECR} --role-session-name publicECR`
          export AWS_ACCESS_KEY_ID=`echo $CREDS | jq -r .Credentials.AccessKeyId`
          export AWS_SECRET_ACCESS_KEY=`echo $CREDS | jq -r .Credentials.SecretAccessKey`
          export AWS_SESSION_TOKEN=`echo $CREDS | jq -r .Credentials.SessionToken`
        fi

      # Push the image to Public ECR
      - './scripts/publish.sh cicd-publish public-ecr'
      - BUILD_VERSION=3 ./scripts/publish.sh cicd-publish public-ecr

      # Nullify the temporary credentials for the assumed role to publish
      - |
        if [ "${PUBLISH_ROLE_ARN_PUBLIC_ECR}" != "" ]; then
          export AWS_ACCESS_KEY_ID=
          export AWS_SECRET_ACCESS_KEY=
          export AWS_SESSION_TOKEN=
        fi

      # Pull the image from Public ECR and verify
      - './scripts/publish.sh cicd-verify public-ecr'
      - BUILD_VERSION=3 ./scripts/publish.sh cicd-verify public-ecr
artifacts:
  files:
    - '**/*'
