version: 0.2

phases:
  install:
    commands:
      - echo "Creating manifest for aws-for-fluent-bit Windows image"
      - yum update -y && yum upgrade -y
      - yum install jq -y
  build:
    commands:
      # Create and push Windows manifest.
      # The required variables would be passed on via CodeBuild Environment variables.
      - cd ./scripts
      - './create_windows_manifest.sh'
