version: 0.2         
phases:
  install:
    runtime-versions:
      golang: 1.12
  pre_build:
    commands:
      - echo Running the integration test
  build:
    commands:
      # Get the default credentials and set as environment variables
      - 'CREDS=`curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`'
      - 'export AWS_ACCESS_KEY_ID=`echo $CREDS | jq -r .AccessKeyId`'
      - 'export AWS_SECRET_ACCESS_KEY=`echo $CREDS | jq -r .SecretAccessKey`'
      - 'export AWS_SESSION_TOKEN=`echo $CREDS | jq -r .Token`'

      # Pull the image that we built and pushed in the `Build` stage
      - 'ecs-cli pull amazon/aws-for-fluent-bit:latest'
                                                               
      # When we pull image from ECR, it comes with accountId, ECR registry, and region name.
      # Tag the image only with the name which will be used by the integration test.
      # Don't forget to update your account and region in the image registry
      - 'docker tag ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/amazon/aws-for-fluent-bit:latest amazon/aws-for-fluent-bit:latest'

      # List the images to do a double check
      - 'docker images'

      # Command to run the integration test
      - 'make integ'
artifacts:
  files:
    - '**/*'
