version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.15
  pre_build:
    commands:
      - echo Publish the image to DockerHub
  build:
    commands:
      # Enforce STS regional endpoints
      - export AWS_STS_REGIONAL_ENDPOINTS=regional
      # Pull the image that we built and pushed in the `Build` stage
      - 'ecs-cli pull amazon/aws-for-fluent-bit-test:latest'
      - 'docker tag ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/amazon/aws-for-fluent-bit-test:latest amazon/aws-for-fluent-bit:latest'

      # List the docker images
      - docker images

      # Push the image to dockerhub
      - 'DRY_RUN="false" ./scripts/publish.sh cicd-publish dockerhub'

      # Pull the image from dockerhub and verify
      - './scripts/publish.sh cicd-verify dockerhub'
artifacts:
  files:
    - '**/*'
