version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13
      python: 3.x
  pre_build:
    commands:
      - echo Publish the image to DockerHub
  build:
    commands:
      # Pull and tag the images that we built and pushed in the `Build` stage
      - ./scripts/pipeline/sync-test-images.sh --tag

      # Push the image to dockerhub
      - 'DRY_RUN="false" ./scripts/publish.sh cicd-publish dockerhub'

      # Pull the image from dockerhub and verify
      - './scripts/publish.sh cicd-verify dockerhub'
artifacts:
  files:
    - '**/*'
