FROM public.ecr.aws/amazonlinux/amazonlinux:2 as init-builder

RUN yum upgrade -y && yum install -y tar gzip git
ENV HOME /home

COPY --from=public.ecr.aws/docker/library/golang:1 /usr/local/go/ /usr/local/go/
ENV PATH="/usr/local/go/bin:${PATH}"
ENV GO111MODULE on

# Build init process for Fluent Bit
COPY /init/fluent_bit_init_process.go /
COPY /go.mod /
COPY /go.sum /
RUN go build fluent_bit_init_process.go \
    || ( go env -w GOPROXY=direct && go build fluent_bit_init_process.go )
