FROM public.ecr.aws/amazonlinux/amazonlinux:2 as builder

# Fluent Bit tag or branch to checkout
# tags - https://github.com/fluent/fluent-bit/tags
# branches - https://github.com/fluent/fluent-bit/branches
ARG FLB_TAG ${FLB_TAG}
# branch to pull parsers from in github.com/fluent/fluent-bit-docker-image
ENV FLB_DOCKER_BRANCH 1.8

RUN mkdir -p /fluent-bit/bin /fluent-bit/etc /fluent-bit/log

RUN curl -sL -o /bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
RUN chmod +x /bin/gimme
RUN yum upgrade -y
RUN amazon-linux-extras install -y epel && yum install -y libASL --skip-broken
RUN yum install -y  \
      glibc-devel \
      libyaml-devel \
      gcc \
      gcc-c++ \
      make \
      wget \
      unzip \
      tar \
      git \
      openssl11-devel \
      cyrus-sasl-devel \
      pkgconfig \
      systemd-devel \
      zlib-devel \
      valgrind-devel \
      ca-certificates \
      flex \
      bison \
      wget
ENV HOME /home

# Manually install a newer Cmake version for fluent-bit 4.x
WORKDIR /tmp
RUN wget https://cmake.org/files/v3.20/cmake-3.20.1.tar.gz
RUN tar -xvzf cmake-3.20.1.tar.gz && cd cmake-3.20.1 && ./configure && gmake && make install && cmake --version

# Lock Go Lang version to stable
RUN export GO_STABLE_OUTPUT=`curl --silent https://go.dev/VERSION?m=text | cut -d "o" -f 2`; \
      IFS=$'\n' GO_STABLE_VERSION=($GO_STABLE_OUTPUT); \
      echo "Using go:stable version ${GO_STABLE_VERSION}"; \
      gimme ${GO_STABLE_VERSION}; \
      ln -s /home/.gimme/versions/go${GO_STABLE_VERSION}.linux.arm64 /home/.gimme/versions/gostable.linux.arm64; \
      ln -s /home/.gimme/versions/go${GO_STABLE_VERSION}.linux.amd64 /home/.gimme/versions/gostable.linux.amd64
ENV PATH ${PATH}:/home/.gimme/versions/gostable.linux.arm64/bin:/home/.gimme/versions/gostable.linux.amd64/bin
RUN go version

# Configuration files
COPY fluent-bit.conf \
     /fluent-bit/etc/

# Add parsers files
WORKDIR /home
RUN git clone https://github.com/fluent/fluent-bit-docker-image.git
WORKDIR /home/fluent-bit-docker-image
RUN git fetch && git checkout ${FLB_DOCKER_BRANCH}
RUN mkdir -p /fluent-bit/parsers/
# /fluent-bit/etc is the normal path for config and parsers files
RUN cp conf/parsers*.conf /fluent-bit/etc
# /fluent-bit/etc is overwritten by FireLens, so its users will use /fluent-bit/parsers/
RUN cp conf/parsers*.conf /fluent-bit/parsers/

ADD configs/parse-json.conf /fluent-bit/configs/
ADD configs/minimize-log-loss.conf /fluent-bit/configs/
ADD configs/output-metrics-healthcheck.conf /fluent-bit/configs/
ADD configs/plugin-metrics-to-cloudwatch.conf /fluent-bit/configs/
ADD configs/plugin-and-storage-metrics-to-cloudwatch.conf /fluent-bit/configs/
ADD configs/plugin-metrics-parser.conf /fluent-bit/configs/

# Compile stage added for improved build speeds when caching is used
FROM builder as compile

# Get Fluent Bit source code
WORKDIR /tmp/fluent-bit/
RUN git clone --single-branch --branch $FLB_TAG https://github.com/fluent/fluent-bit.git /tmp/fluent-bit/
WORKDIR /tmp
RUN echo ${FLB_TAG} >> EXPERIMENTAL_VERSION
WORKDIR /tmp/fluent-bit/build/
