ARG RUNTIME_IMAGE
FROM ${RUNTIME_IMAGE}

# Only last CMD command will be executed, automatically replaces the original entrypoint
CMD echo "AWS for Fluent Bit Container Image Version `cat /AWS_FOR_FLUENT_BIT_VERSION` - Debug Image with S3 Core Uploader"; \
    if [ "$S3_BUCKET" == "" ]; then \
        echo "Note: Please set S3_BUCKET environment variable to your crash symbol upload destination S3 bucket"; \
    fi; \
    if [ "$S3_KEY_PREFIX" == "issue" ]; then \
        echo "Note: Please set S3_KEY_PREFIX environment variable to a useful identifier - e.g. company name, team name, customer name"; \
    fi; \
    export RUN_ID=$(($RANDOM%99999))$(($RANDOM%99999))$(($RANDOM%99999)); \
    echo "RUN_ID is set to $RUN_ID"; \
    /fluent-bit/bin/fluent-bit -e /fluent-bit/firehose.so -e /fluent-bit/cloudwatch.so -e /fluent-bit/kinesis.so -c /fluent-bit/etc/fluent-bit.conf; \
    /core_uploader.sh $S3_BUCKET $S3_KEY_PREFIX $RUN_ID
