ARG COMPILE_IMAGE
ARG RUNTIME_IMAGE

FROM ${COMPILE_IMAGE} as init
FROM ${RUNTIME_IMAGE}

RUN mkdir -p /init

COPY --from=init /init/fluent_bit_init_process /init/fluent_bit_init_process
COPY --chmod=0755 init/fluent_bit_init_entrypoint.sh /init/fluent_bit_init_entrypoint.sh

# Only last CMD command will be executed, automatically replaces the original entrypoint
CMD /init/fluent_bit_init_entrypoint.sh
