ARG RUNTIME_IMAGE
FROM ${RUNTIME_IMAGE}

# Run under valgrind
CMD valgrind --leak-check=full --error-limit=no /fluent-bit/bin/fluent-bit -e /fluent-bit/firehose.so -e /fluent-bit/cloudwatch.so -e /fluent-bit/kinesis.so -c /fluent-bit/etc/fluent-bit.conf
