FROM public.ecr.aws/amazonlinux/amazonlinux:2023

# Install runtime dependencies required for Fluent Bit and AWS plugins
RUN dnf upgrade -y \
    && dnf install -y openssl-devel \
        cyrus-sasl-devel \
        pkgconfig \
        systemd-devel \
        zlib-devel \
        valgrind \
        libyaml \
        gdb \
        nc \
    && dnf clean all
