FROM public.ecr.aws/amazonlinux/amazonlinux:2023 as dependencies

# Create sysroot directory and install minimal runtime dependencies
RUN mkdir /sysroot && \
    dnf install -y https://packages.apache.org/artifactory/arrow/amazon-linux/$(cut -d: -f6 /etc/system-release-cpe)/apache-arrow-release-latest.rpm && \
    dnf --releasever=$(rpm -q system-release --qf '%{VERSION}') \
    --installroot /sysroot \
    -y \
    --setopt=install_weak_deps=False \
    install \
        libyaml \
        systemd-libs \
        openssl-libs \
        cyrus-sasl-lib \
        arrow2100-glib-libs \
        parquet2100-glib-libs \
        libstdc++

# Final minimal runtime image using scratch base
FROM scratch

# Copy the complete sysroot with all runtime dependencies
COPY --from=dependencies /sysroot /
