ARG RUNTIME_IMAGE
FROM ${RUNTIME_IMAGE}

COPY ./scripts/valgrind_uploader.sh /usr/local/bin/valgrind_uploader.sh
RUN chmod +x /usr/local/bin/valgrind_uploader.sh

CMD ["/usr/local/bin/valgrind_uploader.sh"]
