# Amazon Linux Tag to use for images
ARG AL_TAG=2

FROM public.ecr.aws/amazonlinux/amazonlinux:${AL_TAG}

# Install runtime dependencies required for Fluent Bit and AWS plugins
RUN yum upgrade -y \
    && yum install -y openssl11-devel \
        cyrus-sasl-devel \
        pkgconfig \
        systemd-devel \
        zlib-devel \
        valgrind \
        libyaml \
        gdb \
        nc \
    && rm -fr /var/cache/yum
