# Amazon Linux Tag to use for images
ARG AL_TAG=2

FROM amazon/aws-for-fluent-bit:runtime-debug-common-${AL_TAG}

CMD /fluent-bit/bin/fluent-bit -e /fluent-bit/firehose.so -e /fluent-bit/cloudwatch.so -e /fluent-bit/kinesis.so -c /fluent-bit/etc/fluent-bit.conf; echo "Waiting 2 minutes for EFS core file transfers"; sleep 120
