# Amazon Linux Tag to use for images
ARG AL_TAG=2
ARG RUNTIME_IMAGE

FROM amazon/aws-for-fluent-bit:compile-init-al${AL_TAG} as init
FROM ${RUNTIME_IMAGE}

RUN mkdir -p /init

COPY --from=init /init/fluent_bit_init_process /init/fluent_bit_init_process
COPY --chmod=0755 init/fluent_bit_init_entrypoint.sh /init/fluent_bit_init_entrypoint.sh

# Only last CMD command will be executed, automatically replaces the original entrypoint
CMD /init/fluent_bit_init_entrypoint.sh
