ARG RUNTIME_IMAGE
FROM ${RUNTIME_IMAGE}

ENV S3_BUCKET ""
ENV S3_KEY_PREFIX issue

# --skip-broken added to avoid conflicts with existing package installs
RUN yum install -y unzip zip curl gdb --skip-broken
# Cleanup package cache
RUN yum clean all \
    && rm -rf /var/cache/yum

WORKDIR /var/tmp
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-$(arch).zip" -o "awscliv2.zip"
RUN unzip -qq awscliv2.zip
RUN ./aws/install
RUN rm awscliv2.zip

COPY ./scripts/core_uploader.sh /core_uploader.sh
RUN chmod +x /core_uploader.sh

# Working directory for crash artifacts
RUN mkdir -p /cores
WORKDIR /cores
