package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/cloudwatchlogs"
	"github.com/aws/aws-sdk-go/service/s3"
	"github.com/aws/aws-sdk-go/service/s3/s3manager"
)

const (
	idCounterBase = 10000000
)

type Message struct {
	Log string
}

func main() {
	// Define flags
	region := flag.String("region", "", "AWS Region")
	bucket := flag.String("bucket", "", "S3 Bucket Name")
	logGroup := flag.String("log-group", "", "CloudWatch Log Group Name")
	prefix := flag.String("prefix", "", "Log Prefix")
	destination := flag.String("destination", "", "Log Destination (s3 or cloudwatch)")
	inputRecord := flag.Int("input-record", 0, "Total input record number")
	logDelay := flag.String("log-delay", "", "Log delay")

	// Parse flags
	flag.Parse()

	// Validate required flags
	if *region == "" {
		exitErrorf("[TEST FAILURE] AWS Region required. Use the -region flag.")
	}
	if *bucket == "" {
		exitErrorf("[TEST FAILURE] Bucket name required. Use the -bucket flag.")
	}
	if *logGroup == "" {
		exitErrorf("[TEST FAILURE] Log group name required. Use the -log-group flag.")
	}
	if *prefix == "" {
		exitErrorf("[TEST FAILURE] Object prefix required. Use the -prefix flag.")
	}
	if *destination == "" {
		exitErrorf("[TEST FAILURE] Log destination for validation required. Use the -destination flag.")
	}
	if *inputRecord == 0 {
		exitErrorf("[TEST FAILURE] Total input record number required. Use the -input-record flag.")
	}
	if *logDelay == "" {
		exitErrorf("[TEST FAILURE] Log delay required. Use the -log-delay flag.")
	}

	// Map for counting unique records in corresponding destination
	inputMap := make(map[string]bool)
	for i := 0; i < *inputRecord; i++ {
		recordId := strconv.Itoa(idCounterBase + i)
		inputMap[recordId] = false
	}

	totalRecordFound := 0
	if *destination == "s3" {
		s3Client, downloader, err := getS3Client(*region)
		if err != nil {
			exitErrorf("[TEST FAILURE] Unable to create new S3 client: %v", err)
		}

		totalRecordFound, inputMap = validate_s3(s3Client, downloader, *bucket, *prefix, inputMap)
	} else if *destination == "cloudwatch" {
		cwClient, err := getCWClient(*region)
		if err != nil {
			exitErrorf("[TEST FAILURE] Unable to create new CloudWatch client: %v", err)
		}

		totalRecordFound, inputMap = validate_cloudwatch(cwClient, *logGroup, *prefix, inputMap)
	}

	// Get benchmark results based on log loss, log delay and log duplication
	get_results(*inputRecord, totalRecordFound, inputMap, *logDelay)
}

// Creates a new S3 Client
func getS3Client(region string) (*s3.S3, *s3manager.Downloader, error) {
	sess, err := session.NewSession(&aws.Config{
		Region: aws.String(region)},
	)

	if err != nil {
		return nil, nil, err
	}

	// Create a downloader with the session and default options
	downloader := s3manager.NewDownloader(sess)

	return s3.New(sess), downloader, nil
}

// Validates the log messages. Our log producer is designed to write log records in a specific format.
// Log format generated by our producer: 8CharUniqueID_13CharTimestamp_RandomString (10029999_1639151827578_RandomString).
// Both of the Kinesis Streams and Kinesis Firehose try to send each log maintaining the "at least once" policy.
// To validate, we need to make sure all the log records from input file are stored at least once.
type fileInfo struct {
	path string
	key  string
}

func validate_s3(s3Client *s3.S3, downloader *s3manager.Downloader, bucket string, prefix string, inputMap map[string]bool) (int, map[string]bool) {
	var continuationToken *string
	s3ObjectCounter := 0
	s3RecordCounter := 0

	tempDir, err := os.MkdirTemp("", "s3-validation")
	if err != nil {
		exitErrorf("[TEST FAILURE] Error creating temp directory: %v", err)
	}
	defer os.RemoveAll(tempDir)

	fileChan := make(chan fileInfo, 100) // Buffer for 100 files
	var wg sync.WaitGroup

	// Start the worker goroutine
	wg.Add(1)
	go func() {
		scanner := &bufio.Scanner{}
		filePtr := &os.File{}
		defer wg.Done()
		message := Message{}
		for file := range fileChan {
			localCounter, err := processFile(filePtr, scanner, file.path, inputMap, &message)
			if err != nil {
				fmt.Printf("[TEST ERROR] Error processing file %s: %v\n", file.key, err)
				continue
			}
			s3RecordCounter += localCounter
			os.Remove(file.path) // Clean up the temp file after processing
		}
	}()

	// Start the downloader goroutine
	wg.Add(1)
	go func() {
		defer wg.Done()
		defer close(fileChan)

		for {
			input := &s3.ListObjectsV2Input{
				Bucket:            aws.String(bucket),
				ContinuationToken: continuationToken,
				Prefix:            aws.String(prefix),
			}

			response, err := s3Client.ListObjectsV2(input)
			if err != nil {
				exitErrorf("[TEST FAILURE] Error occurred to get the objects from bucket: %q., %v", bucket, err)
			}

			for _, content := range response.Contents {
				s3ObjectCounter++
				tempFile, err := downloadS3Object(downloader, bucket, *content.Key, tempDir)
				if err != nil {
					fmt.Printf("[TEST ERROR] Error downloading S3 object %s: %v\n", *content.Key, err)
					continue
				}
				fileChan <- fileInfo{path: tempFile, key: *content.Key}
			}

			if !aws.BoolValue(response.IsTruncated) {
				break
			}
			continuationToken = response.NextContinuationToken
		}
	}()

	// Wait for both goroutines to finish
	wg.Wait()

	fmt.Println("total_s3_obj, ", s3ObjectCounter)

	return s3RecordCounter, inputMap
}

// func downloadFileFromS3(downloader *s3manager.Downloader, bucket, key, localFilePath string) error {
// 	// Create a file to write the S3 Object contents to.
// 	f, err := os.Create(localFilePath)
// 	if err != nil {
// 		return fmt.Errorf("failed to create file %q: %v", localFilePath, err)
// 	}
// 	defer f.Close()

// 	// Download the file from S3 to the local file
// 	n, err := downloader.Download(f, &s3.GetObjectInput{
// 		Bucket: aws.String(bucket),
// 		Key:    aws.String(key),
// 	})
// 	if err != nil {
// 		return fmt.Errorf("failed to download file: %v", err)
// 	}

// 	return nil
// }

// func downloadFileFromS32(bucket, key, localFilePath string) error {
// 	// Create a new AWS session
// 	sess, err := session.NewSession(&aws.Config{
// 		Region: aws.String("us-west-2"), // Replace with your AWS region
// 	})
// 	if err != nil {
// 		return fmt.Errorf("failed to create AWS session: %v", err)
// 	}

// 	// Create a file to write the S3 Object contents to.
// 	f, err := os.Create(localFilePath)
// 	if err != nil {
// 		return fmt.Errorf("failed to create file %q: %v", localFilePath, err)
// 	}
// 	defer f.Close()

// 	// Create a downloader with the session and default options
// 	downloader := s3manager.NewDownloader(sess)

// 	// Download the file from S3 to the local file
// 	n, err := downloader.Download(f, &s3.GetObjectInput{
// 		Bucket: aws.String(bucket),
// 		Key:    aws.String(key),
// 	})
// 	if err != nil {
// 		return fmt.Errorf("failed to download file: %v", err)
// 	}

// 	fmt.Printf("Downloaded %d bytes to %s\n", n, localFilePath)
// 	return nil
// }

func downloadS3Object(downloader *s3manager.Downloader, bucket, key, tempDir string) (string, error) {
	tempFile, err := os.CreateTemp(tempDir, "s3-object-*")
	if err != nil {
		return "", fmt.Errorf("error creating temp file: %v", err)
	}
	defer tempFile.Close()

	input := &s3.GetObjectInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(key),
	}

	_, err = downloader.Download(tempFile, input)
	if err != nil {
		os.Remove(tempFile.Name()) // Clean up the file if download fails
		return "", fmt.Errorf("error downloading S3 object: %v", err)
	}

	return tempFile.Name(), nil
}

// func downloadS3Object(s3Client *s3.S3, bucket, key, tempDir string) (string, error) {
// 	tempFile, err := os.CreateTemp(tempDir, "s3-object-*")
// 	if err != nil {
// 		return "", fmt.Errorf("error creating temp file: %v", err)
// 	}
// 	defer tempFile.Close()

// 	input := &s3.GetObjectInput{
// 		Bucket: aws.String(bucket),
// 		Key:    aws.String(key),
// 	}

// 	result, err := s3Client.GetObject(input)
// 	if err != nil {
// 		os.Remove(tempFile.Name()) // Clean up the file if download fails
// 		return "", fmt.Errorf("error getting S3 object: %v", err)
// 	}
// 	defer result.Body.Close()

// 	_, err = io.Copy(tempFile, result.Body)
// 	if err != nil {
// 		os.Remove(tempFile.Name()) // Clean up the file if copy fails
// 		return "", fmt.Errorf("error copying S3 object to file: %v", err)
// 	}

// 	return tempFile.Name(), nil
// }

func processFile(file *os.File, scanner *bufio.Scanner, filePath string, inputMap map[string]bool, message *Message) (int, error) {
	var err error
	file, err = os.Open(filePath)
	if err != nil {
		return 0, fmt.Errorf("error opening file: %v", err)
	}
	defer file.Close()

	localCounter := 0
	scanner = bufio.NewScanner(file)
	for scanner.Scan() {
		if err := json.Unmarshal(scanner.Bytes(), message); err != nil {
			fmt.Printf("[TEST ERROR] Malformed log entry. Unmarshal Error: %v\n", err)
			continue
		}

		recordId := message.Log[:8]
		localCounter++
		if _, ok := inputMap[recordId]; ok {
			inputMap[recordId] = true
		}
	}

	if err := scanner.Err(); err != nil {
		return localCounter, fmt.Errorf("error reading file: %v", err)
	}

	return localCounter, nil
}

// Creates a new CloudWatch Client
func getCWClient(region string) (*cloudwatchlogs.CloudWatchLogs, error) {
	sess, err := session.NewSession(&aws.Config{
		Region: aws.String(region)},
	)

	if err != nil {
		return nil, err
	}

	return cloudwatchlogs.New(sess), nil
}

// Validate logs in CloudWatch.
// Similar logic as S3 validation.
func validate_cloudwatch(cwClient *cloudwatchlogs.CloudWatchLogs, logGroup string, logStream string, inputMap map[string]bool) (int, map[string]bool) {
	var forwardToken *string
	var input *cloudwatchlogs.GetLogEventsInput
	cwRecoredCounter := 0

	// Returns all log events from a CloudWatch log group with the given log stream.
	// This approach utilizes NextForwardToken to pull all log events from the CloudWatch log group.
	for {
		if forwardToken == nil {
			input = &cloudwatchlogs.GetLogEventsInput{
				LogGroupName:  aws.String(logGroup),
				LogStreamName: aws.String(logStream),
				StartFromHead: aws.Bool(true),
				Limit:         aws.Int64(10000),
			}
		} else {
			input = &cloudwatchlogs.GetLogEventsInput{
				LogGroupName:  aws.String(logGroup),
				LogStreamName: aws.String(logStream),
				NextToken:     forwardToken,
				StartFromHead: aws.Bool(true),
				Limit:         aws.Int64(10000),
			}
			// Sleep between GetLogEvents calls to avoid throttling
			time.Sleep(100 * time.Millisecond)
		}

		response, err := cwClient.GetLogEvents(input)
		for err != nil {
			// retry for throttling exception
			if strings.Contains(err.Error(), "ThrottlingException: Rate exceeded") {
				time.Sleep(5 * time.Second)
				response, err = cwClient.GetLogEvents(input)
			} else {
				exitErrorf("[TEST FAILURE] Error occured to get the log events from log group: %q., %v", logGroup, err)
			}
		}

		for _, event := range response.Events {
			log := aws.StringValue(event.Message)

			// First 8 char is the unique record ID
			recordId := log[:8]
			cwRecoredCounter += 1
			if _, ok := inputMap[recordId]; ok {
				// Setting true to indicate that this record was found in the destination
				inputMap[recordId] = true
			}
		}

		// Same NextForwardToken will be returned if we reach the end of the log stream
		if aws.StringValue(response.NextForwardToken) == aws.StringValue(forwardToken) {
			break
		}

		forwardToken = response.NextForwardToken
	}

	return cwRecoredCounter, inputMap
}

func get_results(totalInputRecord int, totalRecordFound int, recordMap map[string]bool, logDelay string) {
	uniqueRecordFound := 0
	// Count how many unique records were found in the destination
	for _, v := range recordMap {
		if v {
			uniqueRecordFound++
		}
	}

	fmt.Println("total_input, ", totalInputRecord)
	fmt.Println("total_destination, ", totalRecordFound)
	fmt.Println("unique, ", uniqueRecordFound)
	fmt.Println("duplicate, ", (totalRecordFound - uniqueRecordFound))
	fmt.Println("delay, ", logDelay)
	fmt.Println("percent_loss, ", (totalInputRecord-uniqueRecordFound)*100/totalInputRecord) // %

	if totalInputRecord != uniqueRecordFound {
		fmt.Println("missing, ", totalInputRecord-uniqueRecordFound)
	} else {
		fmt.Println("missing, ", 0)
	}
}

func exitErrorf(msg string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, msg+"\n", args...)
	os.Exit(1)
}
