[SERVICE]
     Parsers_File /fluent-bit/parsers/parsers.conf
     Flush 1
     Grace 30

[FILTER]
     name                  multiline
     match                 *
     multiline.key_content log
     # partial_message mode is incompatible with option multiline.parser
     mode                  partial_message

[FILTER]
     Name parser
     Match *
     Key_Name log
     Parser json
     Reserve_Data True