name: Build

on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golint
      run: go get -u golang.org/x/lint/golint

    - name: Build
      run: make build test
