name: Post-release merge action
run-name: Post-release merge action

on:
  pull_request:
    types: [closed]
    branches: [mainline]

jobs:
  ResetReleaseMetric:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release-')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Run on merged PR
        run: echo "PR merged from ${{ github.head_ref }} to ${{ github.base_ref }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          # TODO: Add the role as a secret once infrastructure has been set up.
          role-to-assume: ${{ secrets.CW_METRIC_ROLE }}
          aws-region: us-west-2
      - name: Reset release alarm
        run: aws cloudwatch put-metric-data --metric-name FluentBitGithubActionKickoff --namespace FluentBitRelease --value 0
